### ISSUE TITLE
Transfer snap ownership to upstream

### ISSUE THREAD

**Issue by flexiondotorg** [asciinema/asciinema-snap#1]
Hello asciinema developers!

I understand asciinema would like to publish the snap authoritatively. The snap is currently published by @markshuttle but we can transfer ownership to you. If you create a snap store brand account for asciinema using a team email address associated with the asciinema.org then we will be able to assign you verified publisher status :heavy_check_mark:  Individual accounts for release managers can be added as collaborators. Here are the instructions:

  * https://forum.snapcraft.io/t/creating-snap-store-brand-accounts/6271

Once ownership had been transferred the build process can be automated via the free [Snapcraft build service](https://build.snapcraft.io) or CI such as [Travis Snap integration](https://docs.travis-ci.com/user/deployment/snaps/) or [Circle Snap Build and Publish](https://circleci.com/docs/2.0/build-publish-snap-packages/).

**Comment by om26er** [comment]
Hey @sickill could you take a look here please :-)

**Comment by ku1ik** [comment]
Hey guys! Sorry for late response, last 1+ month was a bit hectic for me.

I have now registered account with admin@asciinema.org. Tried to register snap name "asciinema" but indeed it is taken :)

Is it possible to add release managers who have email addresses not under asciinema.org domain?

**Comment by popey** [comment]
@sickill To transfer the snap to you, we have a simple process. Start a thread over at https://forum.snapcraft.io/c/store/ and reference this thread. The store team will do the due diligence and initiate a transfer of the snap. Thanks!

**Comment by om26er** [comment]
Can I (a contributor) start a thread as well ? (I committed myself to the maintenance of asciinema snap)

**Comment by popey** [comment]
Technically anyone can start the thread. The store team may ask further questions to feel confident they're transferring the snap from/to the right people :)

**Comment by om26er** [comment]
That is now done. Thanks everyone.
