### ISSUE TITLE
Please enable autobuilds

### ISSUE THREAD

**Issue by om26er** [asciinema/asciinema-snap#3]
We need to enable autobuilds on https://snapcraft.io/build -- that way, a change to this repo will trigger a new build automatically, causing the latest asciinema build to publish.

@sickill could you please do that.

**Comment by ku1ik** [comment]
![obraz](https://user-images.githubusercontent.com/17589/54490981-0155df80-48bb-11e9-9d03-3cfc78a63df0.png)

**Comment by ku1ik** [comment]
I hope I did everything correctly 🤞
